In [54]:
import numpy as np
import matplotlib.pyplot as plt

In [55]:
N = 16

grid = np.zeros((N, N))

In [56]:
agents = [np.array([np.random.randint(0, N), np.random.randint(0, N)]) for k in range(3)]

In [57]:
for agent in agents:
    grid[agent[0], agent[1]] = 1

In [58]:
def draw(agents):
    for agent in agents:
        plt.scatter(agent[0], agent[1])
        plt.xlim([0, N])
        plt.ylim([0, N])
        plt.grid()
        plt.xlabel('x')
        plt.ylabel('y')

In [59]:
dt = 10**(-3)
T = 10
Ns = int(T/(dt))
time = np.linspace(0, T, Ns)

time

array([0.00000000e+00, 1.00010001e-03, 2.00020002e-03, ...,
       9.99799980e+00, 9.99899990e+00, 1.00000000e+01])

In [60]:
agent = agents[0]

In [61]:
agent

array([6, 2])

In [62]:
np.linalg.norm(agents[0] - agents[1])

11.180339887498949

In [64]:
print(agents[0])
print(agents[1])

agents[0] - agents[1]

[6 2]
[ 1 12]


array([  5, -10])